### ISSUE TITLE
Integration in nuxt3 throws "self is not defined" error ...

### ISSUE THREAD

**Issue by s36ast14n** [revolist/vue3-datagrid#26]
Hello friends ...

I never thought it would happen, but this is actually my first github-issue I'm going to send out in this world. I hope I won't start doing that with a stupid question ... 🙈

What I'm trying to do? I've been trying to integrate vue3-datagrid into my nuxt3 app. 

I've created this component:

```
<template>
  <div>
    <v-grid theme="compact" :source="rows" :columns="columns"></v-grid>
  </div>
</template>

<script>
import VGrid from "@revolist/vue3-datagrid"

export default {
  data() {
    return {
      columns: [
        {
          prop: "name",
          name: "First",
        },
        {
          prop: "details",
          name: "Second",
        },
      ],
      rows: [
        {
          name: "1",
          details: "Item 1",
        },
      ],
    }
  },
  components: {
    VGrid,
  },
}
</script>

<style>
#app {
  height: 700px;
  width: 500px;
}
revo-grid {
  height: 100%;
}
</style>
```

Unfortunately it throws the following error:

```
ReferenceError: self is not defined
    at Object.<anonymous> (/Users/s***/Projects/workbench/g***/app/src/frontend/node_modules/@revolist/vue3-datagrid/dist/vgrid.js:1:238)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async __instantiateModule__ (file:///Users/s***/Projects/workbench/g***/app/src/frontend/.nuxt/dist/server/server.mjs:4158:3)
```

Since vue3-datagrid is basically a client-side component, I already assumed that I have to register a plugin for the client-side ... So I added following file (including the suffix ".client") inside the plugins folder:

grid.client.ts:

```
import VGrid from "@revolist/vue3-datagrid";

export default defineNuxtPlugin((nuxtApp) => { nuxtApp.vueApp.component("VGrid", VGrid) });
```

Unfortunately this doesn't work either. Same error. Is there something I'm doing wrong, or is there simply no possibility at the moment to use vue3-datagrid in nuxt3?

Btw: I'm using node version: v18.4.0 and my package.json looks like that:

```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "@typescript-eslint/parser": "^5.30.6",
    "eslint": "^8.7.0",
    "nuxt": "3.0.0-rc.4",
    "prettier": "^2.5.1",
    "typescript": "^4.7.4",
    "vue-eslint-parser": "^9.0.3"
  },
  "dependencies": {
    "@revolist/vue3-datagrid": "^3.1.0",
    "sass": "^1.53.0",
    "vue3-carousel": "^0.1.40",
    "ws": "^8.8.0"
  }
}
```
Thanks a lot in advance! Any help is appreciated!

**Comment by revolist** [comment]
Hello @s36ast14n 
could you please provide codesandbox example the way it's explained here:
https://github.com/revolist/vue3-datagrid/blob/master/.github/ISSUE_TEMPLATE/issue-template.md

this will speedup whole process, because of we need to setup whole environment to make it work

**Comment by naccio8** [comment]
You need to use this method: **plugin/grid.client.ts**

```
import {VGridPlugin} from "@revolist/vue3-datagrid";
export default defineNuxtPlugin(async (nuxtApp) => {
  nuxtApp.vueApp.use(VGridPlugin)
});
```
in page or component .vue

```
<ClientOnly>
  <vue-data-grid theme="compact" :source="rows" :columns="columns" />aa
</ClientOnly>
```
